### PR TITLE
Implement setUserAgentOverride

### PR DESCRIPTION
**Pull request by lukaslueg**
Implements setUserAgentOverride, issue #140

### CODE REVIEW

**Comment by lukaslueg** [comment]
Whoops, the disable-feature commit sneaked up on me. Unrelated, should work though.

**Comment by lukaslueg** [comment]
CI failure seems unrelated. There are still synchronization-problems?!

**Comment by atroche** [comment]
Hmm, not like I've seen before. I wonder what's causing the browser to close early in that test (and only on Mac). I'm re-running CI just to get more information.

**Comment by atroche** [comment]
Interesting, seeing this error:

```

**Comment by atroche** [comment]
Seems like we're calling `getResponseBody` before the page has finished navigating:
```
🏹  [04:59:47.396] - ess_chrome::browser::transport - received response for: 8 "Navigate { url: \"http://127.0.0.1:53836\" }"
🏹  [04:59:47.396] - ess_chrome::browser::tab - Got result: "Ok(NavigateReturnObject { frame_id: \"F46E63BCECFAC48F2714994D5267B1DC\""
📝  [04:59:47.396] - ess_chrome::browser::tab - Navigating a tab to http://127.0.0.1:53836
🏹  [04:59:47.396] - ess_chrome::browser::transport - received response for: 11 "SendMessageToTarget { target_id: None, session_id: Some(\"1661B74BCCA0A5078B4EB30F853F1674\"), message: \"{\\\"method\\\":\\\"Network.getResponseBody\\\",\\\"id\\\":10,\\\"params\\\":{\\\"requestId\\\":\\\"47203A3436C38921F083BD372AB92715\\\"}}\" }"
🏹  [04:59:47.397] - ess_chrome::browser::transport - waiting for response from call registry: 10 "GetResponseBody { request_id: \"47203A3436C38921F083BD372AB92715\" }"
🏹  [04:59:47.399] - ess_chrome::browser - Target info changed: TargetInfo { target_id: "F46E63BCECFAC48F2714994D5267B1DC", target_type: Page, title: "127.0.0.1:53836", url: "http://127.0.0.1:53836/", attached: true, opener_id: None, browser_context_id: Some("291AE78DD4058E70A696692446BD1117") }
🏹  [04:59:47.401] - ess_chrome::browser::transport::waiting_call_registry - Resolving call
🏹  [04:59:47.402] - ess_chrome::browser::transport - received response for: 10 "GetResponseBody { request_id: \"47203A3436C38921F083BD372AB92715\" }"
🏹  [04:59:47.403] - ess_chrome::browser::transport - Message from target isn't recognised: "{\"method\":\"Network.dataReceived\",\"params\":{\"requestId\":\"47203A3436C38921F083BD372AB92715\",\"timestamp\":658.700091,\"dataLength\":187,\"encodedDataLength\":0}}" - data did not match any variant of untagged enum Message
🏹  [04:59:47.406] - ess_chrome::browser::transport - Message from target isn't recognised: "{\"method\":\"Network.loadingFinished\",\"params\":{\"requestId\":\"47203A3436C38921F083BD372AB92715\",\"timestamp\":658.684916,\"encodedDataLength\":315,\"shouldReportCorbBlocking\":false}}" - data did not match any variant of untagged enum Message
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RemoteError { code: -32000, message: "No data found for resource with given identifier" }
```

**Comment by atroche** [comment]
And yet we only call it after we receive 'ResponseReceived'...
https://github.com/atroche/rust-headless-chrome/blob/e3112ac35a4ed96acbf6e83c6e549e9600b14503/src/browser/tab/mod.rs#L218-L229

**Comment by atroche** [comment]
Interestingly, `setRequestInterception` is now deprecated: https://github.com/ChromeDevTools/devtools-protocol/blob/master/changelog.md#roll-protocol-to-r673382. I'm not sure what's supposed to replace it...

**Comment by atroche** [comment]
Aha, fetch apparently: https://github.com/GoogleChrome/puppeteer/blob/6860d73212d2a36fd789a9244667be574f396164/lib/NetworkManager.js#L145

**Comment by atroche** [comment]
@lukaslueg I'm going to merge this despite the CI problems, because they're clearly unrelated.

**Pull request merged**
