### PR TITLE
changed default sleep from 100 to 5 ms

### PR DESCRIPTION
**Pull request by Dowwie**

### CODE REVIEW

**Comment by lukaslueg** [comment]
If we go low on the default sleep time, I'd be great if we had some form of bounded exponential backoff, e.g. 5ms, 25ms, 100ms, 250ms, 250ms, 250ms....

**Comment by Dowwie** [comment]
It's not clear to me whether exponential backoff fits this scenario.  If this were backing off from hammering a Chrome service, then maybe, but this sleeps between checking whether state changed.

**Comment by atroche** [comment]
@Dowwie some of the uses of `Wait` do relatively expensive operations, like multiple RPC calls. Why not just change the timeout used for the navigation check? (That was your specific use case, IIRC from chat)

The backoff idea seems pretty sensible to me.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Dowwie** [comment]
@atroche I see.  Thanks for clarifying that io is involved.  I think exponential can take off a little too quickly so can we start it at 5ms?  Changing just for nav is up to you.

**Comment by atroche** [comment]
Is there a specific problem you ran into that you're trying to solve? Let me know if I can help.

**Comment by Dowwie** [comment]
@atroche adopting backoff may involve changing sleep's type from Duration to ExponentialBackoff, depending on what you prefer for the library.  Changing sleep to Duration would introduce breaking changes that you have to be comfortable with.  Can you think of an alternative?

Backoff in a nutshell:

backoff library:   https://docs.rs/backoff/0.1.3/backoff/

```rust
use backoff::backoff::Backoff;
use backoff::ExponentialBackoff;

let mut backoff = ExponentialBackoff::default();
backoff.max_elapsed_time = None;

let time = backoff.next_backoff();
```

**Comment by Dowwie** [comment]
@atroche next step requires your feedback about changing types

**Comment by atroche** [comment]
@Dowwie the Wait struct could contain an enum of either Duration or ExponentialBackoff, and use the latter by default but the former by users specifying a timeout.

**Comment by Dowwie** [comment]
I'm closing this PR.  Changing sleep or incorporating backoff are tactical solutions.  A headless-chrome puppeteer is intended to be asynchronous.  An async library isn't sleeping nor backing off but rather responding when tasks are ready.

**Comment by Dowwie** [comment]
see https://github.com/atroche/rust-headless-chrome/issues/106

**Pull request closed without merging**
