### PR TITLE
 Make most modules not public

### PR DESCRIPTION
**Pull request by atroche**
Also cheekily included a couple of minor cleanups (deleting unused code).

### CODE REVIEW

**Comment by atroche** [comment]
Should fix https://github.com/atroche/rust-headless-chrome/issues/34

**Comment by atroche** [comment]
Makes output of rustdoc look like this now:

image

**Comment by atroche** [comment]
Will merge this afternoon unless there are any objections

**Comment by lukaslueg** [comment]
There should be integration tests for all public API - if it vanishes from `pub`, something breaks.

**Comment by atroche** [comment]
Agreed. Which modules do you think need to be part of the public API?

**Comment by lukaslueg** [comment]
I have no opinion on that, I don't know the actual library well enough. Everything that does not _need_ to be public should be private and for everything public, there should be an integration test. That is, the integration tests demonstrate the public API or the lack thereof.

**Comment by atroche** [comment]
closing in favour of https://github.com/atroche/rust-headless-chrome/pull/54

**Pull request closed without merging**
