### PR TITLE
Add BoxModel-helpers

### PR DESCRIPTION
**Pull request by lukaslueg**
Some helper functions on `BoxModel` that are handy when writing tests downstream, to check simple geometry (e.g. "is this element roughtly where it's supposed to be")

### CODE REVIEW

**Comment by lukaslueg** [comment]
Just one bit away from the perfect commit id...

**Comment by lukaslueg** [comment]
CI seems to be unrelated but legit. @atroche Any idea if this is #74 in some form?

**Comment by atroche** [comment]
Looking now

**Comment by atroche** [comment]
@lukaslueg I don't think so, because the test that's hanging is solely dealing with `Process`, and not `Browser` / `Tab`. But I've made a couple of small changes that should help debug if it happens again (and which potentially would've fixed it):
https://github.com/atroche/rust-headless-chrome/pull/85

Still not sure exactly how Process::new() could form an infinite loop.

**Comment by lukaslueg** [comment]
Rebased, merge if you want

**Pull request merged**
