### PR TITLE
Add Browser.getWindowBounds, setWindowBounds

### PR DESCRIPTION
**Pull request by lukaslueg**

### CODE REVIEW

**Comment by lukaslueg** [comment]
It's somewhat unclear where this belongs: The protocol part is in the Browser domain, yet we always need a `TargetID` so this is always bound to a tab. I hope the docs make clear that changes to the bounds affect all tabs...

**Comment by lukaslueg** [comment]
Any idea why this fails on MacOS?

**Comment by atroche** [comment]
No idea re. failure on MacOS, sorry.

**Comment by lukaslueg** [comment]
This needs more investigation, the actual behavior seems highly platform dependent and not at all what the docs suggest.

**Comment by atroche** [comment]
@lukaslueg you could include it only for Linux. Seems better than having it for no platforms.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by atroche** [comment]
It works fine on my Mac. I think the problem is just with Travis, so I've disabled the test on Mac and merged this.

**Pull request merged**
