### PR TITLE
Tabs additional functions

### PR DESCRIPTION
**Pull request by RyuuGan**
Add next functionality to tabs:

1. `Tab#close_target`  - closes the tab.
2. `Tab#close_with_unload` - tries to close the tab, but emits `beforeunload` event.
3. `Tab#close(boolean)` - helper function that chooses one of the functions above depending on the boolean parameter.
4. `Tab#activate` - activates current tab (makes it focus).

### CODE REVIEW

**Comment by atroche** [comment]
Thanks! I'm going to try clearing Travis's caches to see if that helps the build not error.

**Comment by atroche** [comment]
@RyuuGan huh, seems like there are some legit failures. Do they happen on your machine?

**Comment by RyuuGan** [comment]
@atroche I checked in Windows 10 and Mac OS x 10.14. All the tests pass.

What is the chrome version of the container? Maybe this is the problem?

**Comment by RyuuGan** [comment]
Looks like I have to wait more (and subrscribe for events to wait until the event from chrome fired (TargetDestroyed), I'll check it out soon. Because container is slower then machine

**Comment by RyuuGan** [comment]
The only error left is:

```
failures:
    src/browser/tab/mod.rs - browser::tab::Tab::get_title (line 939)
test result: FAILED. 9 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
error: test failed, to rerun pass '--doc'
```

But I didn't touched this docs, any ideas?

**Comment by atroche** [comment]
Ah well, let's not worry about that one for now. Great working sticking this out!

**Comment by lanklaas** [comment]
When will this be available in a release? Is there some workaround I can use in the current 0.9.0 release to close a tab?

**Pull request merged**
