### PR TITLE
Add networkLoadingFailed handler

### PR DESCRIPTION
**Pull request by initprism**
It was developed according to the format of the `register_response_handling` method.

### CODE REVIEW

**Comment by mdrokz** [comment]
> It was developed according to the format of the `register_response_handling` method.

Hey sorry for late reply, can you explain more about the changes and what is the intention of adding this method ? thanks

**Comment by Billy-Sheppard** [comment]
Hi @initprism, are you still interested in merging this PR in?

Are you able to shed a little light as to what this PR covers and solves?

**Comment by initprism** [comment]
oh I am sorry for being late.

This PR is an implementation to obtain information about failed HTTP requests. What you get by calling the `register_response_handling` method is information about when the HTTP request completed correctly, not when it failed (like a 404 response).

So in situations like net::ERR_ABORTED , information about it can be obtained by calling `register_loading_failed_handling`.

Event information on this can be found [here](https://chromedevtools.github.io/devtools-protocol/1-2/Network/#event-loadingFailed)

P.s
I implemented this to get a response in situations like [DBD attacks](https://en.wikipedia.org/wiki/Drive-by_download). In headless mode, it is not possible to detect downloaded files when visiting websites through scripts.

**Comment by mdrokz** [comment]
> @mdrokz @Billy-Sheppard oh I am sorry for being late.
> 
> This PR is an implementation to obtain information about failed HTTP requests. What you get by calling the `register_response_handling` method is information about when the HTTP request completed correctly, not when it failed (like a 404 response).
> 
> So in situations like net::ERR_ABORTED , information about it can be obtained by calling `register_loading_failed_handling`.
> 
> Event information on this can be found [here](https://chromedevtools.github.io/devtools-protocol/1-2/Network/#event-loadingFailed)
> 
> P.s I implemented this to get a response in situations like [DBD attacks](https://en.wikipedia.org/wiki/Drive-by_download). In headless mode, it is not possible to detect downloaded files when visiting websites through scripts.

This makes sense and thanks for your contribution i will merge this now

**Review by mdrokz — APPROVED** [review]

**Pull request merged**
