### PR TITLE
Document `Element.call_js_fn`

### LINKED ISSUE #196: Add documentation on `call_js_fn`
Hey!

I've started using `rust-headless-chrome` and I'm having a great experience so far.

I discovered the `call_js_fn` method and thought "oh! this is much easier than the approach I was going to take for what I was trying to do".

I'm thinking that being able to run JS when you just need to quickly grab some data from the browser is something that should be called out in the README - since it's both a common and powerful use case.

Also - I'm still not sure how to use the method. Do I pass a function? Or the contents of a function? Guess and check tells me it's a function - but the `value` on the RemoteObject is None even though I'm returning an array `return [1, 2, 3, 4];`

I'll figure myself out and then submit a PR!

### PR DESCRIPTION
**Pull request by chinedufn**
Closes #196

### CODE REVIEW

**Comment by atroche** [comment]
Happy to merge even before we sort out #198, if you can remove some of the extra comments from the PR.

**Comment by atroche** [comment]
And thanks, I love documentation PRs.

**Comment by chinedufn** [comment]
Awesome

I've removed the commented out tests - anything else you'd like to see changed?

Thanks!

**Comment by chinedufn** [comment]
Anything holding this back from merge that you’d like me to address?

Cheers!

**Comment by atroche** [comment]
@chinedufn sorry for the very slow response!

**Pull request merged**
